//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo_4._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class po_avise_transportations
    {
        public System.Guid uid { get; set; }
        public Nullable<System.Guid> fk_po_avise_request_uid { get; set; }
        public Nullable<System.DateTime> start_time { get; set; }
        public Nullable<double> duration { get; set; }
        public string transport_typ { get; set; }
        public string state { get; set; }
    
        public virtual po_avise_requests po_avise_requests { get; set; }
    }
}
