//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo_3._0.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class inGravureEntities6 : DbContext
    {
        public inGravureEntities6()
            : base("name=inGravureEntities6")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<po_avise_entrance_unloading> po_avise_entrance_unloading { get; set; }
        public virtual DbSet<po_avise_requests> po_avise_requests { get; set; }
        public virtual DbSet<po_avise_transportations> po_avise_transportations { get; set; }
    }
}
