//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo_3._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class po_avise_requests
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public po_avise_requests()
        {
            this.po_avise_entrance_unloading = new HashSet<po_avise_entrance_unloading>();
            this.po_avise_transportations = new HashSet<po_avise_transportations>();
        }
    
        public System.Guid uid { get; set; }
        public Nullable<System.Guid> fk_po_avise_request_uid { get; set; }
        public string material { get; set; }
        public string supplier { get; set; }
        public Nullable<double> qty { get; set; }
        public string uom { get; set; }
        public string unloading { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<po_avise_entrance_unloading> po_avise_entrance_unloading { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<po_avise_transportations> po_avise_transportations { get; set; }
    }
}
