//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo_2._0.Models
{
    using System;
    using System.Collections.Generic;

    public partial class po_avise_requests
    {
        public System.Guid uid { get; set; }
        public string po_no { get; set; }
        public Nullable<System.DateTime> Zeitpunkt { get; set; }
        public string Besteller { get; set; }
        public string item_description { get; set; }
        public string off_loading_advise { get; set; }
        public string Entladung { get; set; }
        public string status { get; set; }

    }
}